### ISSUE TITLE
Project Presentation

### ISSUE THREAD

**Issue by sdoiron25** [matthewjwolff/Sportacus#6]
Determine what is needed as far as in class presentation and written report goes. Powerpoints, demos, etc.

**Comment by matthewjwolff** [comment]
This issue is for the in-class presentation on November 29

**Comment by matthewjwolff** [comment]
Things to put in the presentation:

1. The problem we're trying to solve (understanding and calculating SEC sports statistics)
2. What data is in the database (SEC west stats per game, generic SEC and out of conference)
3. How we're solving the problem (``SELECT`` statements)

Others?
