### ISSUE TITLE
Figuring out what questions we want to answer by SQL statements

### ISSUE THREAD

**Issue by sdoiron25** [matthewjwolff/Sportacus#8]
Title. We need like 10-15 select statements and 4-5 update statements.

**Comment by evenam** [comment]
If we answer this first, we can determine database design and

**Comment by afos2** [comment]
What teams are in the SEC West?
Who has the best record?
...
Who are the top 5 from offense/defense per team?
What team scores the most per category (field goal, td, etc.)?
avg # of x scored against y
if a beat b, who did b beat?
Win percent of scenarios with this or this?
